name: Test

on:
  push:
    branches: [master, main]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v2

      - name: Pushes Results to Web Application Repository
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: test
          dst_owner: Linus-Tay
          dst_path: ./
          dst_repo_name: Capstone-Website
          email: regimelt@hotmail.com