name: Test

on:
  push:
    branches: [master, main]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v2
     
      - name: List Directory
        run: |
          ls

      - name: Create file with information
        uses: finnp/create-file-action@master
          env:
            FILE_NAME: "test.txt"
            FILE_DATA: "${GITHUB_SHA}"
