name: Test

on:
  push:
    branches: [master, main]

env:
  OWNER: Linus-Tay
  REPONAME: StoringHTMLInputs

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: Linus-Tay/store-text-file-in-firebase@v1.8
        with:
          owner: ${{env.OWNER}}
          repoName: ${{env.REPONAME}}
          fileName: "context.txt"
