name: Test

on:
  push:
    branches: [master, main]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v2
     
      - name: List Directory
        run: |
          ls

      - name: Make docker-build.sh Executable
        run: chmod +x ./docker-build.sh

      - name: Create docker image
        run: ./docker-build.sh "${GITHUB_REF#refs/heads/}.${GITHUB_SHA}"
