name: Test

on:
  push:
    branches: [master, main]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v2

      - name: Create file with information
        run: |
          echo "${ GITHUB_REPOSITORY }" > test.txt
          echo "${ GITHUB_SHA }" >> test.txt

      - name: Show file content
        run: |
          cat test.txt
