name: Testing HTML Stuff

on:
  push:
    branches: [master, main]

jobs:
  run-tests:
    name: Run Tests
    using: "composite"

    steps:
      - name: Test Random Generator
        outputs:
          random-number:
            description: "Random number"
            value: ${{ steps.random-number-generator.outputs.random-id }}
        runs:
          using: "composite"
          steps:
            - id: random-number-generator
              run: echo "::set-output name=random-id::$(echo $RANDOM)"
              shell: bash