name: Testing HTML Stuff

on:
  push:
    branches: [master, main]


inputs:
  destinationFolder: # path
    description: 'The folder to copy the files to'
    required: true
    default: 'test'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.filesNo }}

jobs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "::set-output name=filesNo::$(echo $RANDOM)"
      shell: bash